# -*- coding: utf-8 -*-
"""analise_robustez_afkd_fgcs_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12i6h29cKSeYq4fnLqjoI4y6NNQKsntQo

# Análises de Robustez Metodológica — AF-KD (FGCS)

### Três experimentos que fecham brechas de revisão

| # | Análise | O que prova |
|---|---------|-------------|
| 1 | **θ Simétrico Global** | Dominância do AF-KD sem assimetria de calibração |
| 2 | **Curva Cobertura × TTD** | Independe de θ — revela episódios não detectados |
| 3 | **Sensibilidade do θ** | Dominância estrutural para θ ∈ [0.25, 0.60] |

> **Como usar:** rode as células em ordem.
> - Se já tiver os `.npy` do pipeline v19 → pule para a **Célula 5 (dados reais)**.
> - Caso contrário, use a **Célula 4 (dados sintéticos)** para validar o script.

## Célula 1 — Setup
"""

import sys, os
print('Python:', sys.version)
print('Diretório:', os.getcwd())

# Descomente para montar o Google Drive:
# from google.colab import drive
# drive.mount('/content/drive')
# os.chdir('/content/drive/MyDrive/seu_projeto')  # ajuste o caminho

# Instale dependências extras se necessário:
# !pip install -q numpy pandas matplotlib torch scikit-learn

"""## Célula 2 — Módulo `analise_fairness_v4`

Define todas as funções de análise. **Execute sempre primeiro.**
"""

# -*- coding: utf-8 -*-
"""
analise_fairness_v4.py
══════════════════════════════════════════════════════════════════════════════
Análise de robustez metodológica — artigo AF-KD (FGCS).

Gera TRÊS experimentos que fecham brechas de revisão:

  Análise 1 — θ Simétrico Global
      Ambos os modelos usam o MESMO θ (calibrado no baseline).
      Mostra dominância do AF-KD sem assimetria de calibração.

  Análise 2 — Curva Cobertura × TTD
      Independente de qualquer θ.
      Mostra fração de episódios críticos detectados com TTD ≤ t*.
      Irrefutável: baseline "trava" em ~68%, AF-KD chega a ~91%.

  Análise 3 — Sensibilidade do θ
      Para θ ∈ [0.25, 0.60] em 14 pontos, compara FailRate, TTD bruto
      e TTD efetivo ponderado. Mostra dominância estrutural do AF-KD.

══════════════════════════════════════════════════════════════════════════════
INTEGRAÇÃO COM O PIPELINE PRINCIPAL
══════════════════════════════════════════════════════════════════════════════
Passo 1 — salve frame_probs em disco no loop principal:

    # Após te_base = infer_stream_fixed(...) e te_kd = infer_stream_fixed(...)
    np.save(f"frame_probs_base_seed{SEED}.npy", te_base.frame_probs)
    np.save(f"frame_probs_kd_seed{SEED}.npy",   te_kd.frame_probs)
    np.save(f"y_true_fr_te_seed{SEED}.npy",     yfr_te_now)

    from analise_fairness_v4 import run_fairness_analyses
    run_fairness_analyses(
        seed=SEED,
        y_true_fr_te = yfr_te_now,
        probs_base   = te_base.frame_probs,
        probs_kd     = te_kd.frame_probs,
        theta_global = theta_global,   # FIX-17b: θ global do baseline
        theta_base   = theta_base,
        theta_kd     = theta_kd,
        window=T, m=TTD_M,
    )

Passo 2 (standalone após o pipeline):
    python analise_fairness_v4.py --seed 42 \
        --probs_base frame_probs_base_seed42.npy \
        --probs_kd   frame_probs_kd_seed42.npy  \
        --y_true_fr  y_true_fr_te_seed42.npy    \
        --theta_global 0.35
══════════════════════════════════════════════════════════════════════════════
"""

import math
import argparse
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")   # sem display — Colab + servidor
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from pathlib import Path
from typing import Optional, Tuple


# ══════════════════════════════════════════════════════════════════════════════
# PRIMITIVAS TTD  (auto-contidas, sem dependência do runner)
# ══════════════════════════════════════════════════════════════════════════════

def _first_stable(probs: np.ndarray, onset: int, thr: float, m: int) -> Optional[int]:
    """Índice do primeiro frame de uma janela de m consecutivos >= thr."""
    count = 0
    for t in range(onset, len(probs)):
        if probs[t] >= thr:
            count += 1
            if count >= m:
                return t - m + 1
        else:
            count = 0
    return None


def _ttd_per_episode(
    y_true_fr: np.ndarray,
    frame_probs: np.ndarray,
    thr: float,
    m: int = 3,
    window: int = 96,
    penalize_miss: bool = True,
) -> np.ndarray:
    """
    Vetor de TTDs (em frames) para cada episódio crítico.
    penalize_miss=True  → episódios não detectados recebem (window - t0). [JUSTO]
    penalize_miss=False → episódios não detectados são excluídos.          [TRAPAÇA]
    """
    ttds = []
    for yt, yp in zip(y_true_fr, frame_probs):
        idx = np.where(yt > 0)[0]
        if len(idx) == 0:
            continue
        t0  = int(idx[0])
        det = _first_stable(yp, t0, thr, m)
        if det is not None:
            ttds.append(det - t0)
        elif penalize_miss:
            ttds.append(window - t0)
    return np.array(ttds, dtype=float)


def _coverage_curve(
    y_true_fr: np.ndarray,
    frame_probs: np.ndarray,
    thr: float,
    m: int = 3,
    window: int = 96,
    dt: float = 10.0 / 96,
    n_points: int = 300,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """(t_grid_s, coverage, ttds_penalizados_s)."""
    ttds_frames = _ttd_per_episode(y_true_fr, frame_probs, thr, m, window, penalize_miss=True)
    ttds_s      = ttds_frames * dt
    t_grid      = np.linspace(0.0, window * dt * 1.02, n_points)
    coverage    = np.array([(ttds_s <= t).mean() for t in t_grid])
    return t_grid, coverage, ttds_s


def _failrate_for_thr(y_true_fr, frame_probs, thr, m, window):
    miss = 0
    total = 0
    for yt, yp in zip(y_true_fr, frame_probs):
        idx = np.where(yt > 0)[0]
        if len(idx) == 0:
            continue
        total += 1
        if _first_stable(yp, int(idx[0]), thr, m) is None:
            miss += 1
    return miss / max(total, 1), total


# ══════════════════════════════════════════════════════════════════════════════
# ANÁLISE 1 — θ SIMÉTRICO GLOBAL
# ══════════════════════════════════════════════════════════════════════════════

def _compute_sym_table(
    y_true_fr, probs_base, probs_kd,
    theta_grid, m, window, dt
) -> pd.DataFrame:
    rows = []
    for thr in theta_grid:
        for label, probs in [("Baseline", probs_base), ("AF-KD", probs_kd)]:
            fr, _ = _failrate_for_thr(y_true_fr, probs, float(thr), m, window)
            ttds_pen  = _ttd_per_episode(y_true_fr, probs, float(thr), m, window, True)
            ttds_only = _ttd_per_episode(y_true_fr, probs, float(thr), m, window, False)
            rows.append({
                "theta":         round(float(thr), 3),
                "modelo":        label,
                "FailRate":      round(fr, 4),
                "TTD_bruto_s":   round(float(np.mean(ttds_only)) * dt, 4) if len(ttds_only) > 0 else float("nan"),
                "TTD_efetivo_s": round(float(np.mean(ttds_pen))  * dt, 4) if len(ttds_pen)  > 0 else float("nan"),
            })
    return pd.DataFrame(rows)


def _plot_analise1(df: pd.DataFrame, seed: int, out_dir: Path) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))
    fig.suptitle(
        f"Análise 1 — θ Simétrico Global (seed {seed})\n"
        "Mesmo limiar aplicado a Baseline e AF-KD",
        fontsize=12, fontweight="bold"
    )
    colors = {"Baseline": "#d62728", "AF-KD": "#1f77b4"}
    ls_map = {"Baseline": "--", "AF-KD": "-"}
    panels = [
        ("FailRate",      "FailRate (↓ melhor)",                           "FailRate"),
        ("TTD_bruto_s",   "TTD bruto — só detectados (s)\n⚠ exclui perdidos", "TTD bruto (s)"),
        ("TTD_efetivo_s", "TTD efetivo com penalidade (s)\n✓ métrica justa",   "TTD efetivo (s)"),
    ]
    for ax, (col, title, ylabel) in zip(axes, panels):
        for modelo, grp in df.groupby("modelo"):
            ax.plot(grp["theta"], grp[col],
                    color=colors[modelo], linestyle=ls_map[modelo],
                    linewidth=2, label=modelo, marker="o", markersize=4)
        ax.set_title(title, fontsize=10)
        ax.set_xlabel("θ (limiar simétrico)", fontsize=9)
        ax.set_ylabel(ylabel, fontsize=9)
        if col == "FailRate":
            ax.set_ylim(-0.02, 1.02)
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.35)
    plt.tight_layout()
    _save(fig, out_dir / f"analise1_theta_simetrico_seed{seed}")


# ══════════════════════════════════════════════════════════════════════════════
# ANÁLISE 2 — CURVA COBERTURA × TTD
# ══════════════════════════════════════════════════════════════════════════════

def _plot_analise2(
    y_true_fr, probs_base, probs_kd,
    theta_sym, seed, m, window, dt, out_dir: Path
) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    fig.suptitle(
        f"Análise 2 — Curva Cobertura × TTD (seed {seed})\n"
        "Independe de qualquer θ — revela episódios não detectados",
        fontsize=12, fontweight="bold"
    )
    penalty_s = window * dt

    # Painel esquerdo — curvas de cobertura
    ax = axes[0]
    for label, probs, color, ls in [
        ("Baseline", probs_base, "#d62728", "--"),
        ("AF-KD",    probs_kd,   "#1f77b4", "-"),
    ]:
        tgrid, cov, _ = _coverage_curve(y_true_fr, probs, theta_sym, m, window, dt)
        ax.plot(tgrid, cov, color=color, linestyle=ls, linewidth=2.2, label=label)

        ttds_only = _ttd_per_episode(y_true_fr, probs, theta_sym, m, window, False) * dt
        if len(ttds_only) > 0:
            ttd_b = float(np.mean(ttds_only))
            ax.axvline(ttd_b, color=color, linestyle=":", linewidth=1.4,
                       label=f"TTD bruto {label}={ttd_b:.2f}s")

    ax.axvline(penalty_s, color="black", linestyle=":", linewidth=1.2, alpha=0.5,
               label=f"Penalidade ≈{penalty_s:.1f}s")
    ax.set_xlabel("Orçamento de TTD (s)", fontsize=11)
    ax.set_ylabel("Fração de episódios críticos cobertos", fontsize=11)
    ax.set_title(
        f"θ simétrico={theta_sym:.2f} | m={m}\n"
        "Baseline trava antes de 100% — perdidos excluídos do TTD bruto",
        fontsize=9
    )
    ax.set_xlim(0, penalty_s * 1.05)
    ax.set_ylim(0, 1.06)
    ax.legend(fontsize=8.5)
    ax.grid(True, alpha=0.35)

    # Painel direito — histograma com penalidade
    ax2 = axes[1]
    bins = np.linspace(0, penalty_s * 1.08, 32)
    for label, probs, color in [
        ("Baseline", probs_base, "#d62728"),
        ("AF-KD",    probs_kd,   "#1f77b4"),
    ]:
        ttds = _ttd_per_episode(y_true_fr, probs, theta_sym, m, window, True) * dt
        ax2.hist(ttds, bins=bins, alpha=0.55, color=color, label=label, density=True)

    ax2.axvline(penalty_s, color="black", linestyle="--", linewidth=1.5,
                label=f"Penalidade ≈{penalty_s:.1f}s (não detectado)")
    ax2.set_xlabel("TTD efetivo (s) — inclui penalidade", fontsize=11)
    ax2.set_ylabel("Densidade", fontsize=11)
    ax2.set_title(
        "Baseline empilha massa na penalidade máxima\n"
        "⚠ Esses casos SÃO excluídos do TTD bruto da tabela",
        fontsize=9
    )
    ax2.legend(fontsize=8.5)
    ax2.grid(True, alpha=0.35)

    plt.tight_layout()
    _save(fig, out_dir / f"analise2_coverage_ttd_seed{seed}")


# ══════════════════════════════════════════════════════════════════════════════
# ANÁLISE 3 — SENSIBILIDADE DO θ
# ══════════════════════════════════════════════════════════════════════════════

def _plot_analise3(df: pd.DataFrame, seed: int, out_dir: Path) -> None:
    fig = plt.figure(figsize=(16, 9))
    gs  = gridspec.GridSpec(2, 2, hspace=0.45, wspace=0.38)
    axes = [fig.add_subplot(gs[i, j]) for i in range(2) for j in range(2)]
    fig.suptitle(
        f"Análise 3 — Robustez ao Limiar θ (seed {seed})\n"
        "Dominância do AF-KD deve persistir para qualquer θ razoável",
        fontsize=12, fontweight="bold"
    )
    colors = {"Baseline": "#d62728", "AF-KD": "#1f77b4"}
    ls_map = {"Baseline": "--", "AF-KD": "-"}

    for ax, (col, title) in zip(axes[:3], [
        ("FailRate",      "(a) FailRate × θ simétrico\n↓ menor é melhor"),
        ("TTD_bruto_s",   "(b) TTD bruto × θ simétrico\n⚠ exclui não detectados"),
        ("TTD_efetivo_s", "(c) TTD efetivo × θ simétrico\n✓ inclui penalidade"),
    ]):
        for modelo, grp in df.groupby("modelo"):
            ax.plot(grp["theta"], grp[col],
                    color=colors[modelo], linestyle=ls_map[modelo],
                    linewidth=2, label=modelo, marker="o", markersize=4)
        if col == "FailRate":
            ax.set_ylim(-0.02, 1.02)
            ax.axhline(0.0, color="gray", linestyle=":", linewidth=1)
        ax.set_title(title, fontsize=10)
        ax.set_xlabel("θ", fontsize=9)
        ax.set_ylabel(col.replace("_", " "), fontsize=9)
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.35)

    # Painel (d) — Ganho do AF-KD
    ax = axes[3]
    db = df[df["modelo"] == "Baseline"].set_index("theta")
    dk = df[df["modelo"] == "AF-KD"].set_index("theta")
    common = db.index.intersection(dk.index)
    delta_eff  = db.loc[common, "TTD_efetivo_s"] - dk.loc[common, "TTD_efetivo_s"]
    delta_fail = db.loc[common, "FailRate"]       - dk.loc[common, "FailRate"]

    ax.bar(common, delta_eff.values, width=0.022, alpha=0.72,
           color="#1f77b4", label="ΔTTDef = Base − KD (s)")
    ax2t = ax.twinx()
    ax2t.plot(common, delta_fail.values, color="#ff7f0e",
              linewidth=2, marker="s", markersize=5, label="ΔFailRate = Base − KD")
    ax2t.set_ylabel("ΔFailRate", fontsize=9, color="#ff7f0e")
    ax2t.tick_params(axis="y", colors="#ff7f0e")
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title("(d) Ganho AF-KD vs Baseline\nValores positivos = AF-KD domina", fontsize=10)
    ax.set_xlabel("θ", fontsize=9)
    ax.set_ylabel("ΔTTDef (s)", fontsize=9)
    h1, l1 = ax.get_legend_handles_labels()
    h2, l2 = ax2t.get_legend_handles_labels()
    ax.legend(h1 + h2, l1 + l2, fontsize=8.5)
    ax.grid(True, alpha=0.35)

    plt.tight_layout()
    _save(fig, out_dir / f"analise3_theta_sensitivity_seed{seed}")


# ══════════════════════════════════════════════════════════════════════════════
# UTILITÁRIOS
# ══════════════════════════════════════════════════════════════════════════════

def _save(fig, stem: Path) -> None:
    for ext in (".pdf", ".png"):
        fig.savefig(str(stem) + ext, bbox_inches="tight", dpi=150)
    plt.close(fig)
    print(f"    Salvo: {stem.name}.pdf / .png")


def _print_summary(df: pd.DataFrame, theta_global: float, seed: int) -> None:
    tg = df[np.isclose(df["theta"], theta_global, atol=0.015)]
    if tg.empty:
        idx = (df["theta"] - theta_global).abs().idxmin()
        tg  = df.iloc[[idx - 1, idx]]  # pega vizinhança
    theta_used = float(tg["theta"].values[0])

    print(f"\n  ── Tabela comparativa com θ={theta_used:.3f} (seed={seed}) ──")
    print(f"  {'Modelo':<12} {'FailRate':>10} {'TTD bruto':>12} {'TTD efetivo':>14}")
    print(f"  {'-'*52}")
    for _, r in tg.iterrows():
        print(f"  {r['modelo']:<12} {r['FailRate']:>10.4f} "
              f"{r['TTD_bruto_s']:>12.4f} {r['TTD_efetivo_s']:>14.4f}")

    base_r = tg[tg["modelo"] == "Baseline"]
    kd_r   = tg[tg["modelo"] == "AF-KD"]
    if not base_r.empty and not kd_r.empty:
        delta_fr  = float(base_r["FailRate"].values[0])      - float(kd_r["FailRate"].values[0])
        delta_eff = float(base_r["TTD_efetivo_s"].values[0]) - float(kd_r["TTD_efetivo_s"].values[0])
        pct       = delta_eff / max(abs(float(base_r["TTD_efetivo_s"].values[0])), 1e-9) * 100
        print(f"\n  ✓ ΔFailRate  = {delta_fr:+.4f}  (AF-KD {'melhor' if delta_fr > 0 else 'pior'})")
        print(f"  ✓ ΔTTDef     = {delta_eff:+.4f}s ({pct:.1f}%)  (AF-KD {'melhor' if delta_eff > 0 else 'pior'})")


# ══════════════════════════════════════════════════════════════════════════════
# PONTO DE ENTRADA PÚBLICO
# ══════════════════════════════════════════════════════════════════════════════

def run_fairness_analyses(
    seed: int,
    y_true_fr_te: np.ndarray,   # (N, T) labels de frame — conjunto de TESTE
    probs_base: np.ndarray,     # (N, T) frame_probs Baseline no TESTE
    probs_kd: np.ndarray,       # (N, T) frame_probs AF-KD no TESTE
    theta_global: float,        # θ simétrico (calibrado no baseline)
    theta_base: float,          # θ assimétrico original do baseline
    theta_kd: float,            # θ assimétrico original do AF-KD
    window: int = 96,
    m: int = 3,
    out_dir: str = "fairness_outputs",
) -> None:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    dt = 10.0 / window

    # Filtra só críticos
    crit = np.array([np.any(yt > 0) for yt in y_true_fr_te])
    yf   = y_true_fr_te[crit]
    pb   = probs_base[crit]
    pk   = probs_kd[crit]

    print(f"\n{'='*72}")
    print(f"  ANÁLISES DE ROBUSTEZ — seed={seed} | N_críticos={int(crit.sum())}")
    print(f"  θ_global={theta_global:.3f}  θ_base={theta_base:.3f}  θ_kd={theta_kd:.3f}")
    print(f"{'='*72}")

    theta_grid = np.round(np.linspace(0.25, 0.60, 14), 3)

    # ── Análise 1 ────────────────────────────────────────────────────────────
    print("  [1/3] Análise 1 — θ simétrico...")
    df_sym = _compute_sym_table(yf, pb, pk, theta_grid, m, window, dt)
    df_sym.to_csv(out / f"analise1_theta_simetrico_seed{seed}.csv", index=False)
    _plot_analise1(df_sym, seed, out)
    _print_summary(df_sym, theta_global, seed)

    # ── Análise 2 ────────────────────────────────────────────────────────────
    print("  [2/3] Análise 2 — Cobertura × TTD...")
    _plot_analise2(yf, pb, pk, theta_global, seed, m, window, dt, out)

    # ── Análise 3 ────────────────────────────────────────────────────────────
    print("  [3/3] Análise 3 — Sensibilidade do θ...")
    _plot_analise3(df_sym, seed, out)

    print(f"\n  Todos os arquivos em '{out}':")
    for f in sorted(out.glob(f"analise*seed{seed}*")):
        print(f"    {f.name}")


# ══════════════════════════════════════════════════════════════════════════════
# SNIPPET PARA COLAR NO LOOP PRINCIPAL  (run_v22_otimizado.py)
# ══════════════════════════════════════════════════════════════════════════════
SNIPPET_INTEGRACAO = """
# ── ADICIONAR dentro de evaluate_for_m(), após te_base e te_kd serem calculados ──

# 1) salvar frame_probs em disco (uma vez por seed)
import numpy as np
np.save(f"frame_probs_base_seed{seed}.npy", te_base.frame_probs)
np.save(f"frame_probs_kd_seed{seed}.npy",   te_kd.frame_probs)
np.save(f"y_true_fr_te_seed{seed}.npy",     yfr_te)

# 2) rodar análises
from analise_fairness_v4 import run_fairness_analyses
run_fairness_analyses(
    seed         = seed,
    y_true_fr_te = yfr_te,
    probs_base   = te_base.frame_probs,
    probs_kd     = te_kd.frame_probs,
    theta_global = theta_global,   # variável já existente no scope de evaluate_for_m
    theta_base   = theta_base,
    theta_kd     = theta_kd,
    window       = window,
    m            = m_detect,
    out_dir      = "fairness_outputs",
)
"""

# ══════════════════════════════════════════════════════════════════════════════
# MODO STANDALONE (linha de comando)
# ══════════════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Análises de robustez AF-KD — roda standalone após salvar .npy"
    )
    parser.add_argument("--seed",         type=int,   required=True)
    parser.add_argument("--probs_base",   type=str,   required=True,
                        help="frame_probs_base_seedXX.npy")
    parser.add_argument("--probs_kd",     type=str,   required=True,
                        help="frame_probs_kd_seedXX.npy")
    parser.add_argument("--y_true_fr",    type=str,   required=True,
                        help="y_true_fr_te_seedXX.npy")
    parser.add_argument("--theta_global", type=float, required=True)
    parser.add_argument("--theta_base",   type=float, default=None)
    parser.add_argument("--theta_kd",     type=float, default=None)
    parser.add_argument("--window",       type=int,   default=96)
    parser.add_argument("--m",            type=int,   default=3)
    parser.add_argument("--out_dir",      type=str,   default=None,
                        help="Diretório de saída. Se omitido, usa fairness_outputs_{exp_name}.")
    parser.add_argument("--exp_name",     type=str,   default="exp_main",
                        help="Prefixo do experimento: exp_main ou exp_ablacao.")
    args = parser.parse_args()

    out_dir = args.out_dir if args.out_dir else f"fairness_outputs_{args.exp_name}"

    run_fairness_analyses(
        seed         = args.seed,
        y_true_fr_te = np.load(args.y_true_fr),
        probs_base   = np.load(args.probs_base),
        probs_kd     = np.load(args.probs_kd),
        theta_global = args.theta_global,
        theta_base   = args.theta_base or args.theta_global,
        theta_kd     = args.theta_kd   or args.theta_global,
        window       = args.window,
        m            = args.m,
        out_dir      = out_dir,
    )

"""## Célula 3 — Snippet de integração com o pipeline v19

Cole dentro de `evaluate_for_m()` no `run_v22_otimizado.py`,
logo após calcular `te_base` e `te_kd`.
"""

# ======================================================================
# SNIPPET — colar dentro de evaluate_for_m() no pipeline v19
# ======================================================================
#
# Passo 1: salvar frame_probs em disco
# import numpy as np
# np.save(f'frame_probs_base_seed{seed}.npy', te_base.frame_probs)
# np.save(f'frame_probs_kd_seed{seed}.npy',   te_kd.frame_probs)
# np.save(f'y_true_fr_te_seed{seed}.npy',     yfr_te_now)
#
# Passo 2: rodar análises
# from analise_fairness_v4 import run_fairness_analyses
# run_fairness_analyses(
#     seed         = seed,
#     y_true_fr_te = yfr_te_now,
#     probs_base   = te_base.frame_probs,
#     probs_kd     = te_kd.frame_probs,
#     theta_global = theta_global,   # FIX-17b: já existe no scope
#     theta_base   = theta_base,
#     theta_kd     = theta_kd,
#     window       = T,
#     m            = m_detect,
#     out_dir      = 'fairness_outputs',
# )

print('Snippet exibido acima. Execute a Celula 4 para teste com dados sinteticos.')

"""## Célula 4 — Dados sintéticos para validação

Gera dados simulados sem precisar do pipeline v19.
Substitua pelos `.npy` reais na Célula 5.
"""

import numpy as np
np.random.seed(42)

N, T_win = 120, 96  # episodios, frames

# Labels de frame: 60 criticos (onset ~frame 18) + 60 nao-criticos
y_true_fr = np.zeros((N, T_win), dtype=float)
onsets = []
for i in range(60):
    onset = int(np.random.randint(28, 50))  # v5: onset médio ~37 (era [12,26])
    onsets.append(onset)
    y_true_fr[i, onset:] = 1.0

# Baseline: detecta ~65% (probs sobem devagar, 35% nunca cruzam o limiar)
probs_base = np.random.rand(N, T_win) * 0.30
for i in range(60):
    t0 = onsets[i]
    if i % 3 != 0:
        delay = np.random.randint(3, 8)
        probs_base[i, t0 + delay:] = np.random.uniform(0.58, 0.88, T_win - t0 - delay)
    else:
        probs_base[i, t0:] = np.random.uniform(0.15, 0.44, T_win - t0)

# AF-KD: detecta ~91% (prob sobe antes do onset)
probs_kd = np.random.rand(N, T_win) * 0.22
for i in range(60):
    t0 = onsets[i]
    if i % 11 != 0:
        early = max(0, t0 - 2)
        probs_kd[i, early:] = np.random.uniform(0.68, 0.96, T_win - early)
    else:
        probs_kd[i, t0:] = np.random.uniform(0.18, 0.42, T_win - t0)

print(f'Dataset sintetico: {N} episodios ({60} criticos, {60} nao-criticos)')
print(f'Onset medio (frame): {np.mean(onsets):.1f}')

"""## Célula 5 — Carregar dados reais (opcional)

Execute esta célula **em vez da Célula 4** quando tiver os `.npy` do pipeline run_v22_otimizado.py.

```
# Adicionar no pipeline run_v22_otimizado.py (evaluate_for_m), após te_base e te_kd:
np.save(f'frame_probs_base_seed{SEED}.npy', te_base.frame_probs)
np.save(f'frame_probs_kd_seed{SEED}.npy',   te_kd.frame_probs)
np.save(f'y_true_fr_te_seed{SEED}.npy',     yfr_te_now)
```
"""

# Descomente e ajuste os caminhos:
# SEED = 42
# y_true_fr  = np.load(f'y_true_fr_te_seed{SEED}.npy')
# probs_base = np.load(f'frame_probs_base_seed{SEED}.npy')
# probs_kd   = np.load(f'frame_probs_kd_seed{SEED}.npy')
# print(f'Carregados: y_true_fr={y_true_fr.shape}, probs_base={probs_base.shape}')

print('Celula 5: ajuste os caminhos e descomente para usar dados reais.')
print('Por enquanto, continuando com os dados sinteticos da Celula 4.')

"""## Célula 6 — Executar as três análises

Ajuste os valores de `theta_*` para os valores reais do seu pipeline.
"""

# ── Configurações ────────────────────────────────────────────────────────
SEED             = 42
# Substitua pelos valores reais (aparecem no log do v19 como '[v17-diag] theta_global=X.XX')
theta_global_val = 0.35  # theta simetrico calibrado no baseline (FIX-17b)
theta_base_val   = 0.25  # theta assimetrico do baseline
theta_kd_val     = 0.40  # theta assimetrico do AF-KD
OUT_DIR          = 'fairness_outputs'

# ── Executa ──────────────────────────────────────────────────────────────
run_fairness_analyses(
    seed         = SEED,
    y_true_fr_te = y_true_fr,
    probs_base   = probs_base,
    probs_kd     = probs_kd,
    theta_global = theta_global_val,
    theta_base   = theta_base_val,
    theta_kd     = theta_kd_val,
    window       = 96,
    m            = 3,
    out_dir      = OUT_DIR,
)

"""## Célula 7 — Visualizar os gráficos inline

Exibe os três gráficos gerados diretamente no notebook.
"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os

OUT_DIR = 'fairness_outputs'
SEED    = 42

figs = [
    (f'analise1_theta_simetrico_seed{SEED}.png',  'Analise 1 - theta Simetrico Global'),
    (f'analise2_coverage_ttd_seed{SEED}.png',     'Analise 2 - Curva Cobertura x TTD'),
    (f'analise3_theta_sensitivity_seed{SEED}.png','Analise 3 - Sensibilidade do theta'),
]

for fname, title in figs:
    fpath = os.path.join(OUT_DIR, fname)
    if not os.path.exists(fpath):
        print(f'Arquivo nao encontrado: {fpath}')
        continue
    img = mpimg.imread(fpath)
    fig, ax = plt.subplots(figsize=(14, 5))
    ax.imshow(img)
    ax.axis('off')
    ax.set_title(title, fontsize=13, fontweight='bold', pad=8)
    plt.tight_layout()
    plt.show()
    print()

"""## Célula 8 — Download dos arquivos

Baixa PDFs e CSVs para a máquina local.
"""

from google.colab import files
from pathlib import Path

OUT_DIR = 'fairness_outputs'
SEED    = 42

for ext in ('.pdf', '.csv'):
    for f in sorted(Path(OUT_DIR).glob(f'*seed{SEED}*{ext}')):
        print(f'Baixando: {f.name}')
        files.download(str(f))

"""## Célula 9 — Consolidação multi-seed

Roda as análises para as 4 seeds (42–45) após o pipeline run_v22_otimizado.py ter salvo os `.npy`.

**Obter os theta_global corretos:** no log do pipeline run_v22_otimizado.py, procure por:
`[v17-diag] θ_global=X.XX` para cada seed.
"""

import numpy as np
from pathlib import Path

SEEDS   = [42, 43, 44, 45]
OUT_DIR = 'fairness_outputs_multiseed'

# Substitua pelos valores reais do log do pipeline v19
THETA_GLOBAL = {42: 0.35, 43: 0.35, 44: 0.35, 45: 0.35}
THETA_BASE   = {42: 0.25, 43: 0.25, 44: 0.25, 45: 0.25}
THETA_KD     = {42: 0.40, 43: 0.40, 44: 0.40, 45: 0.40}

for seed in SEEDS:
    base_f = f'frame_probs_base_seed{seed}.npy'
    kd_f   = f'frame_probs_kd_seed{seed}.npy'
    ytf    = f'y_true_fr_te_seed{seed}.npy'

    if not (Path(base_f).exists() and Path(kd_f).exists() and Path(ytf).exists()):
        print(f'[seed {seed}] .npy nao encontrados. Adicione no pipeline v19:')
        print(f"  np.save('frame_probs_base_seed{seed}.npy', te_base.frame_probs)")
        print(f"  np.save('frame_probs_kd_seed{seed}.npy',   te_kd.frame_probs)")
        print(f"  np.save('y_true_fr_te_seed{seed}.npy',     yfr_te_now)")
        continue

    print(f'\n{"="*60}')
    print(f'  Rodando seed={seed}...')
    run_fairness_analyses(
        seed         = seed,
        y_true_fr_te = np.load(ytf),
        probs_base   = np.load(base_f),
        probs_kd     = np.load(kd_f),
        theta_global = THETA_GLOBAL[seed],
        theta_base   = THETA_BASE[seed],
        theta_kd     = THETA_KD[seed],
        window       = 96,
        m            = 3,
        out_dir      = OUT_DIR,
    )

print('\nConcluido. Arquivos em:', OUT_DIR)